version: '3.8'

services:
  # Gotenberg service for file conversion
  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
    command:
      - "gotenberg"
      - "--api-port=3000"
      - "--api-timeout=120s"
      - "--log-level=info"
      - "--chromium-disable-web-security=true"
      - "--chromium-disable-javascript=false"
      - "--libreoffice-auto-start=true"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    # Gotenberg needs more resources for LibreOffice and Chromium
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Our Python server for email processing and coordination
  pdf-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DEBUG=false
      - PORT=5000
      - GOTENBERG_URL=http://gotenberg:3000
    restart: unless-stopped
    depends_on:
      gotenberg:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Keep our server lightweight since Gotenberg handles heavy lifting
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

networks:
  default:
    name: email2pdf-network
